name: x86rdrand-benchmark
version: git
version-script: |
    echo $(git describe --tags)
summary: Intel x86 rdrand CPU benchmark
description: x86rdrand-benchmark benchmarks the rdrand random number generator
type: app
grade: stable

confinement: strict

architectures:
    - amd64
    - i386

parts:
    x86rdrand-benchmark:
        plugin: make
        source: .
        build-packages:
            - gcc
            - make
apps:
    x86rdrand-benchmark:
        command: usr/bin/x86rdrand-benchmark

